### PR TITLE
Issue#74 dashboard

### PR DESCRIPTION
**Pull request by yingfeng-iu**
not quite done, just to see what rubocop complains, as I can't get rubocop running on hyrax_batch_ingest branch locally.

### CODE REVIEW

**Comment by yingfeng-iu** [comment]
Andrew, thanks for the review. I'll make changes for #1. As for #2, my consideration is based on the requirement "Installing the gem will add this link to the dashboard". I put this in the engine so the link will be added only if the batch gem is installed. The view stack is like host app - batch gem - hyrax, so the host app still can override whatever batch gem does, if needed. If we move the template to host app, is there a way to ensure it's only triggered when batch gem is installed?

**Comment by afred** [comment]
@yingfeng-iu Yes, we would use a generator to copy the template from within the gem's code, into the host app.

The pattern should follow the Rails convention documented [here](https://guides.rubyonrails.org/generators.html) (search for "copy_file"). It would look something like adding the following changes to [hyrax-batch_ingest/lib/generators/hyrax/batch_ingest/install_generator.rb](https://github.com/samvera-labs/hyrax-batch_ingest/blob/master/lib/generators/hyrax/batch_ingest/install_generator.rb)
```
# frozen_string_literal: true
module Hyrax
  module BatchIngest
    class InstallGenerator < Rails::Generators::Base
      source_root File.expand_path('templates', __dir__)

      # (a bunch of code is already in this generator)

      def override_dashboard_sidebar_repository_content
        copy_file "app/views/hyrax/dashboard/sidebar/_repository_content.html.erb", "app/views/hyrax/dashboard/sidebar/_repository_content.html.erb"
      end
    end
  end
end
```

This would require putting the template at `lib/generators/hyrax/batch_ingest/templates/app/views/hyrax/dashboard/sidebar/_repository_content.html.erb`, which would make sense to me.

With this set up, when you run `rails generate hyrax:batch_ingest:install`, it would run this method, which would copy the file from the gem's code into the host app. If a file already exists in the host app (either from customizations, or from another plugin), then the user will be prompted with a question of whether or not they want to override it.

**Comment by yingfeng-iu** [comment]
@afred thanks for the explanation! that's what i'm looking for. as for #1, you prefer the comment to be added to sidebar_content.html.erb, or is it better to add to _repository_content.html.erb (which is the one being overwritten)?

**Comment by afred** [comment]
@yingfeng-iu oops, that was a typo. I fixed it in the comment -- yes, put the comment in the template that is doing the overwriting :)

**Comment by afred** [comment]
@yingfeng-iu I'm not sure we want to copy the spec into the host application. The spec is something we would want to pass as part of the test suite for this gem. Was there a problem getting it to pass as-is?

**Comment by yingfeng-iu** [comment]
@afred I made the changes you suggested, and retested. Please review again. I'm not sure why codeclimate is complaining about the test, I didn't change anything on that, and it wasn't complaining before.

**Comment by yingfeng-iu** [comment]
@afred: the tests pass as is. I removed the copy part.

**Comment by afred** [comment]
@yingfeng-iu the spec needs to be moved back to `spec/views/hyrax/dashboard/batch_sidebar_spec.rb` in order to run as part of the test suite _and_ for Rubocop to ignore it when evaluating block length.

**Comment by afred** [comment]
Approving and merging over CodeClimate coverage diffs... RSpec and Rubocop are happy.

**Pull request merged**
